---
title: "Alcohol consumption as function of latitude and wealth"
author: "JP"
date: "July 7, 2017"
output: 
  github_document
---

# Overview
This script explores global norms of alcohol consumption. I performed this analysis because I had no idea what alcohol consumption looked like globally, and I wanted to know. 
```{r}
library(breadcrumbs)
library(knitr)
library(powerpack)
library(scales)
library(tidyverse)

source(here::here("file_paths.R"))

theme_set(theme_minimal())
```

```{r global options, include=FALSE}
opts_chunk$set(
  fig.path = 'figs/', fig.show = 'asis', dpi = 300, 
  include = TRUE, echo = TRUE, 
  warning = FALSE, message = FALSE, cache = TRUE
) 
```

```{r load data, include=FALSE}
ds_alcohol <- read_rds(file_alcohol_latlong_gdp)
```

Poking around: 
```{r}
ds_alcohol %>% arrange(desc(ttl_L_pure_alcohol))

ds_alcohol %>% filter(str_detect(country, "R")) %>% arrange(desc(country))

ds_alcohol %>% filter(country == "Russian Federation")
```


```{r}
ds_alcohol %>% 
  mutate(
    lat_abs = abs(latitude),
    ns = ifelse(latitude > 0, "North",
      ifelse(latitude <= 0, "South", NA))
  ) %>% 
  filter(complete.cases(ns)) %>% 
  ggplot(aes(x = lat_abs, y = ttl_L_pure_alcohol, color = ns)) + 
  geom_point() + 
  geom_smooth() + 
  scale_color_discrete("Hemisphere") + 
  scale_x_continuous(breaks = seq(0, 80, by = 10)) + 
  labs(
    title = "People consume more alcohol in countries further from the equator",
    x = "Absolute Value for Latitude",
    y = "Liters of alcohol consumed\nper person per year"
  )
```

```{r}
ds_alcohol %>% 
  ggplot(aes(x = latitude, y = ttl_L_pure_alcohol)) + 
  geom_point(alpha = .75) + 
  geom_smooth() + 
  geom_vline(xintercept = 0, color = "green") + 
  scale_color_discrete("Hemisphere") + 
  scale_x_continuous(breaks = seq(-45, 65, by = 5)) + 
  labs(
    title = "Drinking spike is steeper in the northern hemisphere.",
    x = "Latitude",
    y = "Liters of alcohol consumed per person per year"
  )
```

```{r}
ds_alcohol %>% 
  ggplot(aes(x = latitude, y = ttl_L_pure_alcohol)) + 
  geom_boxplot(aes(group = cut_width(latitude, 5))) + 
  scale_x_continuous(breaks = seq(-65, 65, by = 5), limits = c(-65, 65)) + 
  geom_vline(xintercept = 0, color = "blue") + 
  labs(
    title = "Drinking spikes after 30-degrees north of the equator,\n& 15 degrees south",
    x = "Latitude",
    y = "Liters of alcohol consumed per person per year"
  )
```

```{r}
ds_alcohol %>% 
  mutate(country_ppp_60k = ifelse(ppp > 60e3 | ttl_L_pure_alcohol > 12, country, NA)) %>% 
  ggplot(aes(x = ppp, y = ttl_L_pure_alcohol, label = country_ppp_60k)) + 
  geom_point(alpha = .75) +
  geom_smooth() + 
  scale_x_continuous(breaks = seq(0, 150e3, by = 25e3), labels = dollar) + 
  geom_text(nudge_y = .75)
```

```{r}
ds_alcohol %>% 
  filter(ppp < 5e4) %>% 
  ggplot(aes(x = ppp, y = ttl_L_pure_alcohol)) + 
  geom_point(alpha = .75) + 
  geom_smooth() + 
  scale_x_continuous(breaks = seq(0, 150e3, by = 10e3), labels = dollar) + 
  labs(
    title = wrap("Eliminating wealthy outlier countries we see a strong trend of drinking increasing with wealth", 60),
    x = "GDP per Person (PPP) in USD",
    y = "Liters of alcohol consumed per person per year"
  ) 
```

```{r}
ds_alcohol %>% 
  mutate(
    ppp_f = ifelse(ppp <= 15000, "low",
      ifelse(ppp > 15000 & ppp < 30000, "medium",
      ifelse(ppp >= 30000, "high", NA)
    )),
    ppp_f = factor(ppp_f, levels = c("low", "medium", "high"))
  ) %>% 
  filter(complete.cases(ppp_f)) %>% 
  ggplot(aes(x = latitude, y = ttl_L_pure_alcohol, color = fct_rev(ppp_f))) + 
  geom_point(alpha = .75) + 
  geom_smooth() + 
  geom_vline(xintercept = 0, color = "black") + 
  scale_color_discrete("PPP") + 
  scale_x_continuous(breaks = seq(-45, 65, by = 5)) + 
  labs(
    title = wrap("Wealthy countries buck the trend of higher drinking in the far north", 60),
    x = "Latitude",
    y = "Liters of alcohol consumed per person per year"
  )
```

TBD: Add in religion as a variable. 

High PPP countries in northern latitudes driving the plunge in alcohol consumption:
```{r fig.height=4, fig.width=4}
ds_alcohol %>% 
  filter(latitude > 50, ppp >= 3e4) %>% 
  ggplot(aes(x = latitude, y = ttl_L_pure_alcohol, label = country)) + 
  geom_point(alpha = .75) + 
  geom_smooth() + 
  geom_text(nudge_x = .25, nudge_y = .25, size = 4) + 
  labs(
    title = wrap("Wealthy countries reverse the trend of higher drinking in the far north", 60),
    x = "Latitude",
    y = "Liters of alcohol\nconsumed per person per year"
  )
```

```{r}
ds_alcohol %>% 
  mutate(
    ppp_f = ifelse(ppp <= 15000, "low",
      ifelse(ppp > 15000 & ppp < 30000, "medium",
      ifelse(ppp >= 30000, "high", NA)
    )),
    ppp_f = factor(ppp_f, levels = c("low", "medium", "high"))
  ) %>% 
  filter(
    complete.cases(ppp_f),
    ppp_f == "high",
    latitude > 50) %>% 
  select(country, ttl_L_pure_alcohol, latitude, ppp) %>% 
  arrange(-ttl_L_pure_alcohol) %>% 
  kable() %>% 
  kableExtra::kable_styling()
```



